### ISSUE TITLE
Question about parsing library choice.

### ISSUE THREAD

**Issue by bd82** [kdex/chi#2]
I see there was previously a grammar written using Nearley.
https://github.com/kdex/chi/blob/master/src/old-grammar.ne

Asking as a Parsing Library author:
* What were the reasons you have decided to try using Chevrotain?
  - Missing features?
  - Performance?
  - Other?

* Did you examine other parsing libraries? What capabilities are you looking for in a parsing library?

**Comment by kdex** [comment]
Long, detailed answer incoming…

> What were the reasons you have decided to try using Chevrotain?

For me, it was *very* hard to debug nearley. In my development process, there were no warnings, and many input token sets would just lead to infinite recursion, and I often didn't know how to fix it.

My grammar *kind of* worked, but the longer the input program was, the longer it took. IIRC, I gave up when parsing the following took around 30 minutes:
```js
let f = (x, y, z) => x + y + z;
```
After digging around in their issues, it seemed that for maximum performance, I should try to parse tokens instead of lexemes. Thus, I wrote my own lexer, but measured only minimal gains.

I think nearley has a CLI helper with which you can debug grammars. It expects a string as its input, but since I rolled my own lexer, I had to pass tokens in an array. This made debugging the grammar a PITA.

> Did you examine other parsing libraries? What capabilities are you looking for in a parsing library?
I did, yes. I really tried to like nearley. I made it my first choice because it offered a neat BNF format that I'm already used to from university and manpages. It promised to parse *all kinds of stuff*, so I thought I didn't have to be afraid of left-recursion.

I toyed around with PEG.js before I knew about nearley, but writing PEG grammars is hard, somewhat unconventional and not a lot of fun to maintain.

Nearley was great to get me started, but became relatively unmaintainable for me in just two or three days. The main reason, as the reply to the first question might already give away, was mainly debuggability and performance.

I then found [this benchmark](https://sap.github.io/chevrotain/performance/). It showed that nearley's performance seems to be rather awful in general, so I quickly decided to re-implement the entire grammar with another parsing library. Hence, Chevrotain. 😄

> What capabilities are you looking for in a parsing library?

Obviously, "the ability to parse all kinds of grammars", but that's just wishful thinking. I don't think that there is a parser library where rules such as `E ::= E + E` can be made unambiguous, since it's really the grammars that are the fundamental problem, not so much the library.

I'm *very* content with Chevrotain. The performance is outstanding and even if I was skeptical about it not offering a BNF grammar for me to use, I think that this was the right choice. With nearley, the entire grammar often broke when I edited certain rules, since `data[3]` might suddenly become `data[2]`, etc.

I also love that there are so many building blocks to choose from (`MANY_SEP` would be **so** awesome, if it was bug-free). 😆

If I could make a wish, I'd love some kind of "visually pleasing step-through mode" where I could just use my keyboard to step through the rules, because often times, the rule works in my head, but I didn't take into account that I already consumed a token before it reaches the rule. 

If you have cloned and executed the infinite-recursion branch I was pointing you to, you probably also realized that I use [my own library](https://github.com/kdex/print-log)  for printing debug messages, errors, etc, because I can barely work productively when all my output has the same color. To me, colors and nice formatting are just as important in error traces as they are in your editor for syntax highlighting. I'd love if more projects did that by default, with an option to turn colors off if your terminal is weird (gulp and babel, for instance, both do that).

I also tend to look for good ECMAScript 2015 (and later) support when I choose ES libraries, in general. For example, that's a thing that annoys me with Chevrotain: I was curious about why I have to say:

```js
class ChiParser extends Parser {
	constructor() {
		this.RULE("Statement", () => {
			// …
		});
	}
}
```

instead of putting every rule in its own method, binding it to name, like so:

```js
class ChiParser extends Parser {
	constructor() {
		// …
	}
	Statement() {
		return this.RULE(…);
	}
}
```

Or even why I can't just import `RULE` etc. and then use them like so:

```js
import { RULE, Parser } from "chevrotain";
class ChiParser extends Parser {
	constructor() {
		// …
	}
	Statement() {
		return new RULE(…);
	}
}
```

If you have any further questions, just ask ahead. 👍

**Comment by bd82** [comment]
Thanks for the in-depth feedback @kdex 

### Visual debugging

> If I could make a wish, I'd love some kind of "visually pleasing step-through mode" where I could just use my keyboard to step through the rules, because often times, the rule works in my head, but I didn't take into account that I already consumed a token before it reaches the rule.

This is a very good idea. Could be part of the Dev Mode feature.
- There is already Syntax Diagrams support:
   https://github.com/SAP/chevrotain/tree/master/diagrams
- And the Dev mode is supposed to add tracing support.

So if generic pre/post hooks are added for the DSL methods those hooks can trigger animations
on the diagrams and/or textual tracing.

btw except the visually pleasing part you can just debug the grammar as plain JavaScript code
in your favorite IDE. The problem with this is that when debugging the parser 
The grammar is mixed with the semantic actions so it tends to be verbose.

I'm creating a solution for this which will allow **automatic** creation of a concrete syntax tree and running a visitor on the CST **after** the parsing flow.
So the grammar file should only deal with the syntax which will also make it easier to debug and maintain. This means grammar files would look like [this](https://github.com/SAP/chevrotain/blob/master/examples/grammars/json/json_es6.js#L82)
No semantics, just DSL methods.


### EcmaScript Standard

>I also tend to look for good ECMAScript 2015 (and later) support when I choose ES libraries, in general. For example, that's a thing that annoys me with Chevrotain: I was curious about why I have to say ...

The syntax you proposed would construct the RULE **every time** the class method is called.
This RULE function wraps the user provided grammar with additional logic to handle
error recovery, parser state updates and builds other internal data structures, it 
should only be called **once** per rule, the result of RULE is a function which
may be invoked **thousands** of times (for large enough inputs) in a single text parsing...

TypeScript provides class fields which are suitable for this purpose and also look "cleaner".
[Example of class fields](https://github.com/SAP/chevrotain/blob/master/examples/implementation_languages/typescript/typescript_json.ts#L38)

In EcmaScript there is a [stage 2 proposal](https://github.com/tc39/proposal-class-public-fields) for a similar construct. Perhaps you can find a Babel plugin for this syntax.

**Comment by kdex** [comment]
Are these syntax diagrams the same diagrams from the playground? They are helpful, but I haven't used them for debugging so far. The trace that my eyes will follow in the diagram might not necessarily be the trace that chevrotain actually uses internally, so I would be cautious with them.

The CST approach sounds very interesting. I could see many benefits maintaining the grammar; what's the expected way of transforming the CST to a custom structure? Just recurse over it and create such a structure myself?

About ECMAScript: Ah, yes, I see. And yes, I think babel has been supporting class fields for some time as well. Chi also uses them in some places; but overly long constructors weren't my only fear. The other annoyance I felt was that the first argument of `RULE` is the rule's name. So if you write it like [this](https://github.com/SAP/chevrotain/blob/master/examples/implementation_languages/typescript/typescript_json.ts#L38), you'll be redundant, repeating `json` twice, thus making the constructor approach a little more "elegant". 😢

Is the following doable? Note that the invocation of `RULE` only receives a function.

```js
class ChiParser extends Parser {
	Statement = this.RULE(() => { … });
	constructor() {
		// …
	}
}
```

**Comment by bd82** [comment]
> Are these syntax diagrams the same diagrams from the playground?

Yes.

> the trace that my eyes will follow in the diagram might not necessarily be the trace that chevrotain actually uses internally.

It would **be the same one**, that is the purpose of those hooks I described.
If it is possible to trace to the console the correct information from inside the parser
It would also be possible to visually animate the diagrams using the same valid information.

> The CST approach sounds very interesting. I could see many benefits maintaining the grammar; what's the expected way of transforming the CST to a custom structure?

Initially you will have to recurse over it manually.
But I will create visitor utilities over it in the future (near one hopefully).

> Is the following doable? Note that the invocation of RULE only receives a function.

**Probably not**. I will need stronger capabilities in ECMAScript to implement this.
Chevrotain is actually implemented using "poor man's macros" by analyzing(parsing) the text (Function.toString) passed to RULE to figure out the grammar structure. 
But for the syntax you are describing I'll need proper macros like in LISP.
