### ISSUE TITLE
Suggestion: Add support for if/unless/else statements next :)

### ISSUE THREAD

**Issue by kristianmandrup** [kdex/chi#5]
Hi, I'm trying to use this Chi language as the base for my own language in order to learn how to use Chevrotain. I'm trying to add if/unless/else support. I see you already added `If` and `Else` in the lexer, but not yet in the parser or interpreter.

This is what I have so far:

```js
		this.RULE("ifElseStatement", () => {
			this.OR({
				DEF: [{
					/* With Else clause and block */
					ALT: () => {
						this.CONSUME(If);
						this.SUBRULE(this.expression);
						this.SUBRULE(this.block);
						this.CONSUME(Else);
						this.SUBRULE(this.block);
					}
				}, {
					/* Just an if block */
					ALT: () => {
						this.CONSUME(If);
						this.SUBRULE(this.expression);
						this.SUBRULE(this.block);
					}
				}]
			});
		});
```

Is this the right approach at all?

Very vaguely in the `transform`

```js
export function transform(cst) {
	const {
		children
	} = cst;
	switch (cst.name) {
		case "ifStatement":
			{
				const {
					condition,
					block
				} = children;
				const start = 5;
				const end = 5;
				const location = {
					start,
					end
				};
				return new IfStatement(location, condition, block);
			}
		case "ifElseStatement":
			{
				const {
					condition,
					block
				} = children;
				const start = 5;
				const end = 5;
				const location = {
					start,
					end
				};
				return new IfElseStatement(location, condition, block);
			}
```

Not sure if it is better to handle this case as one abstraction or to split it out? (also in the Rule part above)

```js
export class IfStatement extends Statement {
	constructor(location, condition, block) {
		super(location);
		this.condition = condition;
		this.block = block;
	}
}

export class IfElseStatement extends Statement {
	constructor(location, {
		ifStmt,
		elseStmt
	}) {
		super(location);
		this.condition = ifStmt.condition;
		this.block = ifStmt.block;
		this.elseCondition = elseStmt.condition;
		this.elseBlock = elseStmt.block;
	}
}
```

Ideally I'd like to generate an Esprima compatible AST... Would be delighted if you could help me out a bit with what you've learned so far. Thanks.

**Comment by bd82** [comment]
Sorry for butting in 😄 

note the prefix:

```javascript
this.CONSUME(If);
this.SUBRULE(this.expression);
this.SUBRULE(this.block);
```

is identical between the two options.
and that "expression" probably can be of **unlimited length**.

> if 1 > 2
if 1 > 2 && 3 > 4
if 1 > 2 && 3 > 4 && 5 > 6
...

These **theoretically** unlimited number of tokens will have to be consumed in order to **distinguish** between the two alternatives. Now this is possible but would require
backtracking and would be inefficient and manually implemented by the user with GATES.

The simpler solution would be to extract the common prefix and have the else part
as an optional part. 

```javascript
this.CONSUME(If);
this.SUBRULE(this.expression);
this.SUBRULE(this.block);
this.OPTION(() => {
   this.CONSUME(Else);   
   //...
})
```

**Comment by kristianmandrup** [comment]
Oh, wow! Thanks! Makes sense. My first day with Chevrotain and haven't written a compiler since 2nd year in college, long time ago! Lots of fun :) Cheers!
Hope to see some progress on your repo again soon...

**Comment by kdex** [comment]
@kristianmandrup Thanks for your input! I've been in the middle of basing some parts of chi's grammar on ECMAScript, which is why my recent activity is only in the [dev branch](https://github.com/kdex/chi/tree/dev). It's quite a fundamental change to chi, as I also took the liberty to remove confusing "features" such as automatic semicolon insertion (ASI) from the language.

Once the things that I advertise in `README.md` work to a satisfying degree, I'll commit in `master` again. Cheers! 😄

@bd82 Thanks so much for helping out! Much obliged!

**Comment by bd82** [comment]
@kdex remember that ECMAScript was initially created in 10 days
and later developed by a **committee** over many years 😄  

So I would not be worried much about "ignoring" the bad parts.
